# Generated by Django 4.1.1 on 2022-09-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPLOYEE_ID', models.IntegerField()),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(max_length=255)),
                ('EMAIL', models.CharField(max_length=255)),
                ('PHONE_NUMBER', models.IntegerField()),
                ('HIRE_DATE', models.DateField()),
                ('JOB_ID', models.CharField(max_length=255)),
                ('SALARY', models.IntegerField()),
                ('COMMISSION_PCT', models.IntegerField()),
                ('MANAGER_ID', models.IntegerField()),
                ('DEPARTMENT_ID', models.IntegerField()),
            ],
        ),
    ]
