# Generated by Django 4.1.1 on 2022-09-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emp_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='COMMISSION_PCT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='PHONE_NUMBER',
            field=models.CharField(max_length=255),
        ),
    ]
