# Generated by Django 4.1.1 on 2022-09-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_emp_details_commission_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='COMMISSION_PCT',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
    ]
