# Generated by Django 4.1.1 on 2022-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_emp_details_commission_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='COMMISSION_PCT',
            field=models.IntegerField(),
        ),
    ]
