# Generated by Django 4.1.1 on 2022-09-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_emp_details_commission_pct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_details',
            name='EMPLOYEE_ID',
        ),
    ]
